### ISSUE TITLE
支持使用oss吗

### ISSUE THREAD

**Issue by wangkai147** [mjt233/saltedfishcloud-backend#3]
支持使用oss吗

**Comment by mjt233** [comment]
> 支持使用oss吗

目前不支持使用OSS，不过对OSS的支持已经在规划中。
开发这个系统的过程中也有考虑到使用本地文件系统之外的存储，目前有以验证插件开发和存储拓展的可行性为目的的实验性插件-Hadoop存储插件来实现对HDFS的支持。

就现阶段而言，开发一个支持新的存储模式的插件还算简单，参考sfc-ext-hadoop-store模块用较少代码量就能实现一个新的存储插件。

最近的开发重心主要集中在了插件模块上，现在也初步成型了。下一步的计划就是稍微改造下存储相关的功能来支持同时注册多个存储服务，之后就是尝试编写各种不同的文件存储服务了（如FTP、Samba、WebDav、MinIO、、阿里云盘、百度网盘...）。

**Comment by mjt233** [comment]
已完成基于Amazon S3标准的OSS对象存储插件开发，见tag: 2.8.0-RELEASE/release: v2.8.0.0
